(in-package :com.sondesh.database)

(defparameter *county* 
  (mapcar #'(lambda (town) (cl-ppcre:regex-replace-all "[ \\-\\&\\.']" (string-upcase town) ""))
	  (mappend #'identity
  '(("Bedfordshire") ("Berkshire") ("Buckinghamshire") ("Cambridgeshire") ("Cheshire")
			 ("Cornwall") ("Cumberland") ("Derbyshire") ("Devon") ("Dorset") ("Durham")
			 ("Essex") ("Gloucestershire") ("Hampshire") ("Herefordshire") ("Hertfordshire")
			 ("Huntingdonshire") ("Kent") ("Lancashire") ("Leicestershire") ("Lincolnshire")
			 ("Middlesex") ("Norfolk") ("Northamptonshire") ("Northumberland")
			 ("Nottinghamshire") ("Oxfordshire") ("Rutland") ("Shropshire")
			 ("Somerset" "bath and north east sommerset") ("Staffordshire") ("Suffolk") ("Surrey")
			 ("Sussex") ("Warwickshire") ("Westmorland")
			 ("Wiltshire") ("Worcestershire") ("Yorkshire") ("north lincolnshire")
			 ("North Riding") ("East Riding") ("West Riding") ("gwynedd")
			 ("Anglesey" "Sir Fon") ("Brecknockshire" "Sir Frycheiniog")
			 ("Caernarfonshire" "Sir Gaernarfon") ("Carmarthenshire" "Sir Gaerfyrddin")
			 ("Cardiganshire" "Ceredigion") ("Denbighshire" "Sir Ddinbych")
			 ("Flintshire" "Sir Fflint") ("Glamorgan" "Morgannwg") ("greater manchester")
			 ("Merioneth" "Meirionnydd") ("Monmouthshire" "Sir Fynwy") ("greater london")
			 ("Montgomeryshire" "Sir Drefaldwyn") ("Pembrokeshire" "Sir Benfro")
			 ("Radnorshire" "Sir Faesyfed") ("Aberdeenshire") ("Angus" "Forfarshire") ("Argyllshire")
			 ("Ayrshire") ("Banffshire") ("Berwickshire") ("Buteshire") ("Cromartyshire")
			 ("Caithness") ("Clackmannanshire") ("Dumfriesshire") ("Dunbartonshire" "Dumbartonshire")
			 ("East Lothian" "Haddingtonshire") ("Fife") ("Inverness-shire") ("Kincardineshire")
			 ("Kinross-shire") ("Kirkcudbrightshire") ("Lanarkshire") ("Midlothian" "Edinburghshire")
			 ("Morayshire") ("Nairnshire") ("Orkney") ("Peeblesshire") ("Perthshire") ("Renfrewshire")
			 ("Ross-shire") ("Roxburghshire") ("Selkirkshire") ("Shetland") ("Stirlingshire")
			 ("Sutherland") ("West Lothian" "Linlithgowshire") ("Wigtownshire")
    ("Avon" "Cleveland"" Cotswolds" "Cumbria" "East Anglia" "East Midlands" "East Sussex"
     "Greater London" "Greater Manchester" "Humberside" "Isle of Wight" "Isles of Scilly"
     "Lake District" "Lancashire" "Leicestershire" "Lincolnshire" "Merseyside" "Norfolk"
     "North Yorkshire" "Northamptonshire" "Northumberland" "Northumbria" "Nottinghamshire"
     "Oxfordshire" "Rutland" "Shropshire" "Somerset" "South Yorkshire" "Staffordshire"
     "Suffolk" "Surrey"     "Tyne and Wear"     "Warwickshire"     "West Country"     "West Midlands"
     "West Sussex"     "West Yorkshire"     "Wiltshire"     "Worcestershire"     "Yorkshire")
     ))))

(defparameter *area* '("LONDON" "WALTON-ON-THAMES" "GREAT YARMOUTH" "LOWER EARLEY"))

(defparameter *town* 
  (delete-duplicates (mapcar #'(lambda (town) (cl-ppcre:regex-replace-all "[ \\-\\&\\.']" (string-upcase town) ""))
  '("Worcester" "Upton Upon Severn" "Stourport-on-Severn"
  "Redditch" "Pershore" "Overbury" "Malvern Wells" "Malvern" "Kidderminster"
  "Kempsey" "Kemerton" "Hagley" "Evesham" "Droitwich" "Bromsgrove" "Broadway"
  "Blakedown" "Bewdley"
 "Wootton Bassett" "Winsley" "Wilton" "Westbury" "West Kington"
  "Warminster" "Trowbridge" "Tidworth" "Swindon" "Salisbury" "Potterne"
  "Pickwick" "Pewsey" "Monkton Farleigh" "Mere" "Melksham" "Marlborough"
  "Malmesbury" "Lacock" "Highworth" "Durrington" "Devizes" "Cricklade"
  "Corsham" "Chiseldon" "Chippenham" "Calne" "Broughton Gifford"
  "Bradford on Avon" "Biddestone" "Avebury" "Amesbury"
 "Yeadon" "Wetherby" "Wakefield" "Todmorden" "Thornton"
  "Sowerby Bridge" "Slaithwaite" "Shipley" "Pudsey" "Pontefract" "Oxenhope"
  "Otley" "Ossett" "Normanton" "Morley" "Mirfield" "Meltham" "Liversedge"
  "Leeds" "Keighley" "Ilkley" "Huddersfield" "Horsforth" "Holmfirth"
  "Heckmondwike" "Hebden Bridge" "Haworth" "Halifax" "Elland" "Dewsbury"
  "Denby Dale" "Darrington" "Cowling" "Cleckheaton" "Castleford" "Calverley"
  "Burley in Wharfedale" "Brighouse" "Bradford" "Boston Spa" "Birkenshaw"
  "Bingley" "Batley" "Aberford"
 "Worthing" "West Chiltington" "Warnham" "Walberton"
  "Tillington" "Storrington" "Steyning" "Southwater" "South Lancing" "Sompting"
  "Shoreham-by-Sea" "Selsey" "Scayne's Hill" "Rustington" "Rusper"
  "Robertsbridge" "Pulborough" "Plaistow" "Petworth" "Partridge Green"
  "Midhurst" "Lurgashall" "Littlehampton" "Kirdford" "Keymer" "Hurstpierpoint"
  "Horsham" "Hickstead" "Henfield" "Haywards Heath" "Hassocks" "Handcross"
  "Gatwick" "Findon" "Fernhurst" "Faygate" "East Preston" "East Grinstead"
  "Cuckfield" "Crawley" "Chichester" "Burgess Hill" "Bognor Regis"
  "Billingshurst" "Barnham" "Arundel" "Angmering"
 "Wolverhampton" "Willenhall" "West Bromwich" "Wednesfield"
  "Wednesbury" "Warley" "Walsall" "Tipton" "Sutton Coldfield" "Stourbridge"
  "Solihull" "Smethwick" "Rowley Regis" "Oldbury" "Lye" "Kingswinford"
  "Heath Town" "Halesowen" "Edgbaston" "Earlswood" "Dudley" "Coventry"
  "Cotteridge" "Brierly Hill" "Bloxwich" "Blackheath" "Birmingham" "Bilston"
  "Berkswell" "Aston" "Amblecote" "Aldridge"
 "Yettington" "Yetminster" "Yeovil" "Yelverton"
  "Worth Matravers" "Wootton Basset" "Woolacombe" "Wookey Hole" "Winsley"
  "Winsford" "Wincanton" "Wimborne" "Wilton" "Williton" "Whitstone"
  "Wheddon Cross" "Weymouth" "Westward Ho!" "Westleigh" "Westbury"
  "West Kington" "West Down" "Wells" "Wellington" "Wedmore" "Warminster"
  "Wareham" "Wadebridge" "Verwood" "Uffculme" "Truro" "Trowbridge"
  "Tresco" "Totnes" "Torpoint" "Topsham" "Tolpuddle" "Tiverton"
  "Tintagel" "Tidworth" "Templecombe" "Teignmouth" "Tavistock" "Taunton"
  "Swindon" "Swanage" "Sturminster Newton" "Street"
  "Stratton-on-the-Fosse" "Stokenham" "Stoke" "St. Minver" "St. Keverne"
  "St. Just" "St. Ives" "St. Germans"
  "St. Columb Major" "St. Blazey" "St. Austell" "St. Agnes" "Sparkford"
  "Sowton" "Southbourne-on-Sea" "South Petherton" "South Perrott"
  "South Molton" "South Brent" "Somerton" "Sidmouth" "Shirwell"
  "Sherborne" "Shepton Mallet" "Shebbear" "Shaldon" "Shaftesbury"
  "Sennen" "Seaton" "Sandford" "Saltash" "Salisbury" "Salcombe"
  "Redruth" "Rattery" "Ramsbury" "Purton" "Puddletown" "Priddy"
  "Potterne" "Porthleven" "Port Isaac" "Poole" "Polzeath" "Polperro"
  "Plymouth" "Pickwick" "Pewsey" "Perranporth" "Penzance" "Penryn"
  "Pennymoor" "Parracombe" "Parkstone" "Par" "Padstow" "Ottery St. Mary"
  "Okehampton" "Newton Abbot" "Newquay" "Nether Stowey" "Mullion"
  "Mousehole" "Moretonhampstead" "Monkton Farleigh" "Minehead"
  "Mildenhall" "Midsomer Norton" "Mevagissey" "Merton" "Mere" "Melksham"
  "Mawnan Smith" "Martock" "Marldon" "Marlborough" "Market Lavington"
  "Marazion" "Malmesbury" "Lynton" "Lynmouth" "Lympstone" "Lyme Regis"
  "Lostwithiel" "Looe" "Lizard" "Little Torrington" "Liskeard" "Lifton"
  "Launceston" "Langton Matravers" "Langport" "Lacock" "Knowle Village"
  "Kingsteignton" "Kingsbridge" "Ivybridge" "Ilminster" "Horningsham"
  "Honiton" "Holwell" "Holsworthy" "Holbeton" "Highworth" "Highbridge"
  "Herodsfoot" "Hemyock" "Helston" "Heathfield" "Hayle" "Hatherleigh"
  "Hatch Beauchamp" "Harbertonford" "Halsetown" "Gunnislake"
  "Great Torrington" "Glastonbury" "Gillingham" "Frome" "Fowey"
  "Flaxpool" "Ferndown" "Falmouth" "Exmouth" "Exeter" "Evercreech"
  "Durrington" "Dulverton" "Drewsteignton" "Dorchester" "Dolton"
  "Devizes" "Dawlish" "Davidstow" "Dartmouth" "Curry Rivel" "Cullompton"
  "Croyde" "Cricklade" "Crewkerne" "Crediton" "Cranborne" "Coverack"
  "Corsham" "Corfe Castle" "Combe Martin" "Colyford" "Clovelly"
  "Chudleigh" "Christchurch" "Chiseldon" "Chippenham" "Cheddar"
  "Charmouth" "Chard" "Chapel Amble" "Challacombe" "Castle Combe"
  "Camelford" "Camborne" "Calne" "Callington" "Burrington"
  "Burnham-on-Sea" "Budleigh Salterton" "Bude" "Buckfastleigh" "Bruton"
  "Broughton Gifford" "Broadstone" "Bridport" "Bridgwater" "Braunton"
  "Bradworthy" "Bradninch" "Bradford on Avon" "Bovey Tracey" "Bournemouth"
  "Boscastle" "Bodmin" "Blandford St. Mary" "Blandford Forum" "Bideford"
  "Biddestone" "Berrynarbor" "Beckington" "Beaworthy" "Barnstaple"
  "Banwell" "Bampton" "Babbacombe" "Axminster" "Avebury" "Ashburton"
  "Appledore" "Amesbury" "Allerford" "Aldbourne" "Abbotskerswell"
  "Abbotsbury"
 "Wootton Wawen" "Wolston" "Wishaw" "Whitnash" "Wellesbourne"
  "Warwick" "Studley" "Stratford-upon-Avon" "Southam" "Shipston on Stour"
  "Rugby" "Polesworth" "Nuneaton" "Market Bosworth" "Long Itchington"
  "Leamington Spa" "Lapworth" "Ladbroke" "Kineton" "Kenilworth" "Hockley Heath"
  "Gaydon" "Dunchurch" "Coleshill" "Claverdon" "Binley Woods" "Bedworth"
  "Atherstone" "Alcester"
 "Whitley Bay" "Whickham" "Washington" "Wallsend" "Tynemouth"
  "Sunderland" "Southwick" "South Shields" "North Shields"
  "Newcastle-upon-Tyne" "Longbenton" "Jesmond" "Jarrow" "Houghton-le-Spring"
  "Hebburn" "Gosforth" "Gateshead" "Blaydon" "Backworth"
 "Worcester Park" "Woking" "Witley" "Windlesham" "Whyteleafe"
  "Weybridge" "Westhumble" "Westcott" "West Molesey" "West End" "West Byfleet"
  "Warlingham" "Walton-on-Thames" "Virginia Water" "Tongham" "Thames Ditton"
  "Tadworth" "Surbiton" "Sunbury-on-Thames" "Staines" "Shere" "Shepperton"
  "Shalford" "Sanderstead" "Salfords" "Reigate" "Redhill" "Purley" "Peaslake"
  "Oxted" "Oxshott" "Nutfield" "New Malden" "New Haw" "Mytchett" "Morden"
  "Mitcham" "Merstham" "Lingfield" "Lightwater" "Leatherhead" "Laleham"
  "Knaphill" "Kingswood" "Kew" "Kenley" "Horley" "Hindhead" "Haslemere"
  "Guildford" "Great Bookham" "Godstone" "Godalming" "Frimley" "Frensham"
  "Farnham" "Ewell" "Esher" "Epsom" "Englefield Green" "Egham" "Effingham"
  "East Molesey" "East Horsley" "Dorking" "Cranleigh" "Cobham" "Claygate"
  "Chobham" "Chiddingfold" "Chessington" "Chertsey" "Charlwood" "Chaldon"
  "Caterham" "Carshalton" "Capel" "Camberley" "Byfleet" "Brockham" "Bookham"
  "Bisley" "Banstead" "Bagshot" "Ashtead" "Ashford" "Ash" "Alfold"
  "Addlestone"
 "Woodbridge" "Wherstead" "Sudbury" "Stratford St. Mary"
  "Stowmarket" "Stanton" "Southwold" "Snape" "Sizewell" "Saxmundham" "Otley"
  "Newmarket" "Needham Market" "Nayland" "Mildenhall" "Lowestoft"
  "Long Melford" "Leiston" "Lavenham" "Lakenheath" "Kesgrave" "Ipswich"
  "Holbrook" "Haverhill" "Halesworth" "Hacheston" "Framsden" "Framlingham"
  "Felixstowe" "Eye" "Debenham" "Culford Park" "Clare" "Bury St. Edmunds"
  "Bures" "Bungay" "Beccles" "Barton Mills" "Aldeburgh"
 "Wombourne" "Uttoxeter" "Tutbury" "Tamworth" "Stone"
  "Stoke-on-Trent" "Stafford" "Shenstone" "Rugeley" "Penkridge"
  "Newcastle-under-Lyme" "Lichfield" "Leek" "Keele" "Hixon" "Hednesford"
  "Hanley" "Essington" "Eccleshall" "Cannock" "Burton-upon-Trent" "Burntwood"
  "Biddulph" "Audley" "Alton"
 "Wombwell" "Wentworth" "Thrybergh" "Sheffield" "Rotherham"
  "Penistone" "Parkgate" "Hatfield Woodhouse" "Ecclesfield" "Doncaster"
  "Dinnington" "Bawtry" "Barnsley"
 "Yeovil" "Wookey Hole" "Winsford" "Wincanton" "Williton"
  "Wheddon Cross" "Wells" "Wellington" "Wedmore" "Templecombe" "Taunton"
  "Street" "Stratton-on-the-Fosse" "South Petherton" "Somerton"
  "Shepton Mallet" "Priddy" "Nether Stowey" "Minehead" "Midsomer Norton"
  "Martock" "Langport" "Ilminster" "Highbridge" "Hatch Beauchamp" "Glastonbury"
  "Frome" "Flaxpool" "Evercreech" "Dulverton" "Curry Rivel" "Crewkerne"
  "Cheddar" "Chard" "Burnham-on-Sea" "Bruton" "Bridgwater" "Beckington"
  "Banwell" "Allerford"
 "Wroxeter" "Whittington" "Whitchurch" "Wem" "Telford"
  "Shrewsbury" "Shifnal" "Oswestry" "Norbury" "Newport" "Newcastle"
  "Market Drayton" "Madeley" "Lydbury North" "Ludlow" "Kemberton" "Iron Bridge"
  "Ellesmere" "Cleobury Mortimer" "Church Stretton" "Chirbury" "Broseley"
  "Bridgnorth" "Bishop's Castle" "Alveley"
 "Uppingham" "Ridlington" "Oakham"
 "Wroxton" "Woodstock" "Witney" "Wheatley" "Weston-on-the-Green"
  "Watlington" "Wantage" "Wallingford" "Thame" "Sydenham" "Summertown"
  "Steventon" "Steeple Aston" "Stanton Harcourt" "South Stoke" "Oxford"
  "Milton" "Middle Barton" "Long Hanborough" "Kirtlington" "Kingham"
  "Kidlington" "Horspath" "Hook Norton" "Henley-on-Thames" "Harwell"
  "Garsington" "Fifield" "Faringdon" "Eynsham" "Enstone" "Dorchester" "Didcot"
  "Churchill" "Cholsey" "Chipping Norton" "Chinnor" "Checkendon" "Charlbury"
  "Chalgrove" "Chadlington" "Carterton" "Burford" "Brightwell Baldwin" "Botley"
  "Bloxham" "Bicester" "Banbury" "Bampton" "Appleford" "Adderbury" "Abingdon"
 "Worksop" "West Bridgford" "Tuxford" "Tollerton"
  "Sutton-in-Ashfield" "Sutton on Trent" "Southwell" "Retford" "Ravenshead"
  "Radcliffe on Trent" "Papplewick" "Nottingham" "Newark" "Mansfield" "Lowdham"
  "Langar" "Kirkby-in-Ashfield" "Huthwaite" "Hucknall" "Eastwood" "Costock"
  "Chilwell" "Calverton" "Bingham" "Beeston"
 "Yarm" "Wylam" "Widdrington" "Whitley Bay" "Whickham"
  "West Auckland" "Washington" "Wallsend" "Tynemouth" "Thornaby-on-Tees"
  "Teesside" "Sunderland" "Stockton-on-Tees" "Stanley" "Spennymoor"
  "South Shields" "Shildon" "Sedgefield" "Seahouses" "Seaham" "Saltburn"
  "Riding Mill" "Redcar" "Prudhoe" "Ponteland" "Peterlee" "Otterburn"
  "Nunthorpe" "North Shields" "Newton Aycliffe" "Newcastle-upon-Tyne"
  "Morpeth" "Mohope" "Middlesbrough" "Marske-by-Sea" "Longbenton"
  "Lanchester" "Jesmond" "Jarrow" "Houghton-le-Spring" "Hexham"
  "Heddon-on-the-Wall" "Hebburn" "Haydon Bridge" "Haverton Hill"
  "Hartlepool" "Haltwhistle" "Gosforth" "Gateshead" "Ebchester"
  "Easington" "Eaglescliffe" "Durham" "Darlington" "Cramlington"
  "Cornhill-On-Tweed" "Corbridge" "Consett" "Chilton" "Chester-le-Street"
  "Blyth" "Blaydon" "Bishop Auckland" "Billingham" "Berwick-upon-Tweed"
  "Belford" "Bedlington" "Beadnell" "Barnard Castle" "Bamburgh"
  "Backworth" "Ashington" "Alnwick" "Allendale Town"
 "Wylam" "Seahouses" "Rothbury" "Riding Mill" "Prudhoe"
  "Ponteland" "Otterburn" "Morpeth" "Mohope" "Hexham" "Heddon-on-the-Wall"
  "Haydon Bridge" "Haltwhistle" "Cramlington" "Cornhill-On-Tweed" "Corbridge"
  "Blyth" "Berwick-upon-Tweed" "Belford" "Bedlington" "Beadnell" "Bamburgh"
  "Ashington" "Alnwick" "Allendale Town"
 "Wootton" "Woodnewton" "West Haddon" "Wellingborough"
  "Towcester" "Thrapston" "Sywell" "Stoke Bruerne" "Rushden" "Roade"
  "Ravensthorpe" "Pitsford" "Oundle" "Northampton" "Kettering"
  "Irthlingborough" "Irchester" "Horton" "Higham Ferrers" "Gretton"
  "Grafton Regis" "Duston" "Daventry" "Crick" "Corby" "Burton Latimer"
  "Broughton" "Brixworth" "Braunston" "Brackley" "Blisworth"
 "York" "Whitley" "Whitby" "Tockwith" "Thirsk" "Tadcaster"
  "Stokesley" "Staithes" "Skipton" "Settle" "Selby" "Scarborough"
  "Robin Hood's Bay" "Ripon" "Richmond" "Pickering" "Pateley Bridge"
  "Northallerton" "Middleham" "Malton" "Malham" "Long Preston" "Leyburn"
  "Lealholm" "Knaresborough" "Kellington" "Ingleton" "Hemingbrough" "Helmsley"
  "Hawes" "Harrogate" "Great Ayton" "Filey" "Egton" "East Layton" "Easingwold"
  "Cawood" "Bedale" "Barlby" "Bagby"
 "Wymondham" "Wroxham" "Wells-next-the-Sea" "Thornham" "Thetford"
  "Snettisham" "Sheringham" "Norwich" "North Walsham" "Mundesley" "Ludham"
  "Loddon" "King's Lynn" "Kettlestone" "Hunstanton" "Holt" "Harleston"
  "Great Yarmouth" "Fakenham" "Easton" "Downham Market" "Ditchingham" "Diss"
  "Dereham" "Cromer" "Cringleford" "Cley next the Sea" "Cawston" "California"
  "Burnham Market" "Bodham" "Blakeney" "Banham" "Bacton" "Aylsham" "Aylmerton"
  "Attleborough" "Aslacton" "Acle"
 "West Kirby" "Wallasey" "Upton" "Thornton Hough" "Thatto Heath"
  "St. Helens" "Southport" "Rock Ferry" "Rainhill" "Rainford" "Prescot"
  "Prenton" "Port Sunlight" "Newton-le-Willows" "Moreton" "Liverpool"
  "Litherland" "Ledsham" "Knowsley" "Kirkby" "Hoylake" "Heswall" "Formby"
  "Crosby" "Bromborough" "Bootle" "Birkenhead" "Birkdale" "Beechwood"
  "Bebington" "Aintree"
 "Woodhall Spa" "Weston" "Stragglethorpe" "Stickney" "Stamford"
  "Spilsby" "Spalding" "Sleaford" "Skegness" "Metheringham" "Market Rasen"
  "Market Deeping" "Mablethorpe" "Louth" "Lincoln" "Kirton" "Ingoldmells"
  "Horncastle" "Holbeach" "Grantham" "Goulceby" "Gainsborough"
  "Donington on Bain" "Crowland" "Cranwell" "Corringham" "Caistor" "Bourne"
  "Boston" "Billinghay" "Alford"
 "Wigston" "Whetstone" "Stoneygate" "Shepshed" "Ratby"
  "Quorn" "Oadby" "Newtown Linford" "Narborough" "Mountsorrel" "Melton Mowbray"
  "Measham" "Market Harborough" "Lutterworth" "Loughborough" "Leicester"
  "Kibworth Harcourt" "Kegworth" "Hinckley" "Groby" "Fleckney" "Countesthorpe"
  "Coalville" "Charnwood" "Castle Donington" "Broughton Astley" "Blaby"
  "Barrow-on-Soar" "Ashby-de-la-Zouch"
 "Wrightington Bar" "Wrea Green" "Whitworth" "Whalley"
  "Waterfoot" "Trawden" "Thornton" "St. Annes" "Skelmersdale" "Rossendale"
  "Rawtenstall" "Quernmore" "Preston" "Preesall" "Poulton-le-Fylde" "Pilling"
  "Penwortham" "Parbold" "Padiham" "Oswaldtwistle" "Ormskirk" "Nelson"
  "Morecambe" "Lytham St. Anne's" "Longridge" "Leyland" "Lancaster" "Kirkham"
  "Heysham" "Haslingden" "Grindleton" "Great Harwood" "Garstang" "Fleetwood"
  "Failsworth" "Euxton" "Darwen" "Croston" "Colne" "Clitheroe" "Cleveleys"
  "Chorley" "Chipping" "Carnforth" "Burnley" "Brock" "Broadley" "Blackpool"
  "Blackburn" "Belmont" "Barrowford" "Barnoldswick" "Bacup" "Appley Bridge"
  "Altham" "Adlington" "Accrington" "Abbeystead"
 "Workington" "Windermere" "Whitehaven" "Ulverston"
  "Staveley" "St. Bees" "Sedbergh" "Ravenglass" "Penrith" "Newby Bridge"
  "Milnthorpe" "Millom" "Maryport" "Kirkby-in-Furness" "Kirkby Stephen"
  "Kirkby Lonsdale" "Keswick" "Kendal" "Hawkshead" "Great Asby"
  "Grasmere" "Grange-over-Sands" "Gosforth" "Egremont" "Eamont Bridge"
  "Dalton-in-Furness" "Crosby Garrett" "Cockermouth" "Cartmel" "Carlisle"
  "Broughton-in-Furness" "Bowness-on-Windermere" "Bassenthwaite"
  "Barrow-in-Furness" "Ambleside" "Alston"
 "Woodchurch" "Whitstable" "Westerham" "West Malling" "Walderslade"
  "Tunbridge Wells" "Tonbridge" "Thanet" "Teynham" "Tenterden" "Swanscombe"
  "Swanley" "Sundridge" "Strood" "Staplehurst" "Staple" "Southborough"
  "Sittingbourne" "Sheerness" "Sevenoaks" "Sandwich" "Rochester" "Ramsgate"
  "Rainham" "Otford" "Orpington" "Meopham" "Margate" "Marden" "Maidstone"
  "Lympne" "Lyminge" "Lydd" "Lordswood" "Longfield" "Leysdown-on-Sea"
  "Lamberhurst" "Kennington" "Hythe" "Horton Kirby" "Hoo St. Werburgh"
  "Hollingbourne" "High Halstow" "Herne Bay" "Headcorn" "Hawkhurst" "Hadlow"
  "Greenhithe" "Gravesend" "Goudhurst" "Gillingham" "Folkestone" "Faversham"
  "Eynsford" "Erith" "Edenbridge" "East Peckham" "Dymchurch" "Dover" "Deal"
  "Dartford" "Crayford" "Cranbrook" "Cliffe Woods" "Chislehurst" "Chatham"
  "Charing" "Canterbury" "Broadstairs" "Borough Green" "Biddenden"
  "Bexleyheath" "Beckenham" "Aylesford" "Ashford" "Arpinge"

 "Yarmouth" "Wroxall" "Ventnor" "Shanklin" "Sandown" "Ryde"
  "Newport" "Newchurch" "Freshwater" "Cowes"
 "Withernsea" "Sutton-on-Hull" "Snaith" "Scunthorpe"
  "Pocklington" "Patrington" "Market Weighton" "Kingston-upon-Hull" "Immingham"
  "Howden" "Hornsea" "Hessle" "Grimsby" "Goole" "Driffield" "Cottingham"
  "Cleethorpes" "Brigg" "Bridlington" "Bishop Burton" "Beverley"
  "Barton-upon-Humber" "Barrow upon Humber"
 "Wormley" "Whitwell" "Welwyn Garden City" "Welwyn"
  "Welham Green" "Watford" "Ware" "Waltham Cross" "Tring" "Stevenage"
  "St. Albans" "Sawbridgeworth" "Royston" "Rickmansworth" "Radlett"
  "Potters Bar" "Northaw" "New Barnet" "Markyate" "Little Hadham" "Letchworth"
  "Knebworth" "King's Langley" "Kimpton" "Hoddesdon" "Hitchin"
  "Hertingfordbury" "Hertford" "Hemel Hempstead" "Hatfield" "Harpenden"
  "Elstree" "Chorleywood" "Chipperfield" "Cheshunt" "Bushey" "Buntingford"
  "Broxbourne" "Borehamwood" "Bishop's Stortford" "Berkhamsted" "Barnet"
  "Ashwell" "Abbots Langley"
 "Wormsley" "Weobley" "Symonds Yat" "St. Weonards"
  "Ross-on-Wye" "Leominster" "Ledbury" "Kinnersley" "Kington" "Kingsland"
  "Hereford" "Hatfield" "Docklow" "Bishop's Frome"
 "Yateley" "Winchfield" "Winchester" "Wickham" "Whiteley"
  "Whitchurch" "West Town" "Waterlooville" "Warsash" "Waltham Chase" "Upton"
  "Totton" "Titchfield" "Tadley" "Stockbridge" "St. Mary Bourne" "Southsea"
  "Southampton" "Rotherwick" "Romsey" "Ringwood" "Portsmouth" "Petersfield"
  "Odiham" "Oakley" "North Baddesley" "New Milton" "New Alresford" "Netley"
  "Milford on Sea" "Middle Wallop" "Lyndhurst" "Lymington" "Liphook"
  "Lee-on-the-Solent" "Kingsclere" "Hythe" "Horndean" "Hook" "Hedge End"
  "Havant" "Hartley Wintney" "Hambledon" "Hamble" "Gosport" "Fordingbridge"
  "Fleet" "Farnborough" "Fareham" "Fair Oak" "Eversley" "Emsworth" "Eastleigh"
  "Denmead" "Curdridge" "Cowplain" "Clanfield" "Chandler's Ford" "Burley"
  "Buriton" "Brockenhurst" "Bramdean" "Bordon" "Blackwater" "Beaulieu"
  "Basingstoke" "Andover Down" "Andover" "Alton" "Alresford" "Aldershot"
 "Worsley" "Wigan" "Westhoughton" "Wardle" "Urmston"
  "Tyldesley" "Timperley" "Stockport" "Salford" "Royton" "Rochdale"
  "Ramsbottom" "Radcliffe" "Prestwich" "Oldham" "Northenden" "Marple"
  "Manchester" "Littleborough" "Leigh" "Hyde" "Horwich" "Heywood" "Farnworth"
  "Eccles" "Dukinfield" "Droylsden" "Didsbury" "Denton" "Chorlton" "Cheadle"
  "Carrington" "Bury" "Bramhall" "Bowdon" "Bolton" "Ashton-Under-Lyne"
  "Ashton-in-Makerfield" "Altrincham"

 "Wotton-under-Edge" "Toddington" "Tewkesbury" "Tetbury"
  "Stroud" "Stow-on-the-Wold" "Stonehouse" "Staunton" "Somerford Keynes"
  "Quenington" "Painswick" "Northleach" "Newnham" "Newent" "Nailsworth"
  "Moreton-in-Marsh" "Minchinhampton" "Lydney" "Lechlade-on-Thames" "Kemble"
  "Hawling" "Gloucester" "Forthampton" "Fairford" "Dymock" "Dursley"
  "Cirencester" "Cinderford" "Churchdown" "Chipping Sodbury" "Chipping Campden"
  "Cheltenham" "Charlton Kings" "Chalford" "Brockworth" "Bredon" "Bream"
  "Bourton-on-the-Water" "Berkeley" "Apperley" "Amberley"
 "Writtle" "Witham" "Widdington" "Wickford" "White Roding"
  "Wethersfield" "Westcliff" "Walton-on-the-Naze" "Waltham Abbey" "Tollesbury"
  "Tiptree" "Tilbury" "Thundersley" "Thaxted" "Stansted" "Stanford Le Hope"
  "Southend-on-Sea" "South Woodham Ferrers" "Shoeburyness" "Shenfield"
  "Saffron Walden" "Romford" "Rochford" "Rayleigh" "Purfleet" "Pitsea"
  "Pilgrims Hatch" "Nazeing" "Marks Tey" "Manningtree" "Maldon" "Loughton"
  "Leigh-on-Sea" "Langham" "Lamarsh" "Kelvedon Hatch" "Ingatestone" "Ilford"
  "Hornchurch" "Hockley" "Harwich" "Harlow" "Halstead" "Hadleigh"
  "Great Dunmow" "Grays" "Felsted" "Epping" "Crays Hill" "Colchester"
  "Coggeshall" "Clacton-on-Sea" "Chigwell" "Chelmsford" "Canvey Island"
  "Burnham-on-Crouch" "Buckhurst Hill" "Brightlingsea" "Brentwood" "Braintree"
  "Bradwell-on-Sea" "Borley" "Bobbingworth" "Billericay" "Benfleet" "Basildon"
  "Barling" "Audley End" "Asheldham"
 "Wadhurst" "Uckfield" "Ticehurst" "St. Leonards on Sea"
  "Seaford" "Rye" "Rottingdean" "Rotherfield" "Ringmer" "Polegate" "Northiam"
  "North Chailey" "Newick" "Newhaven" "Lewes" "Hove" "Herstmonceux"
  "Heathfield" "Hastings" "Hartfield" "Hailsham" "Forest Row" "Eastbourne"
  "Ditchling" "Crowborough" "Chailey" "Burwash" "Brighton" "Bexhill-on-Sea"
  "Battle" "Alfriston"
 "Wymeswold" "Worksop" "Wootton" "Woodnewton"
  "Woodhall Spa" "Wirksworth" "Willington" "Wigston" "Whetstone"
  "Whaley Bridge" "Weston" "West Haddon" "West Bridgford" "Wellingborough"
  "Tuxford" "Towcester" "Tollerton" "Thrapston" "Tansley" "Sywell"
  "Swadlincote" "Sutton-in-Ashfield" "Sutton on Trent" "Stoneygate"
  "Stonebroom" "Stoke Bruerne" "Stickney" "Stamford" "Spondon" "Spilsby"
  "Spalding" "Southwell" "Somercotes" "Sleaford" "Skegness" "Shepshed"
  "Rushden" "Roade" "Ripley" "Retford" "Repton" "Ravensthorpe"
  "Ravenshead" "Ratby" "Radcliffe on Trent" "Quorn" "Pitsford"
  "Papplewick" "Oundle" "Oadby" "Nottingham" "Northampton"
  "Newtown Linford" "Newbold" "Newark" "New Mills" "Mountsorrel"
  "Moulton" "Morton" "Metheringham" "Melton Mowbray"
  "Melbourne" "Measham" "Matlock" "Market Rasen" "Market Harborough"
  "Market Deeping" "Mapperley" "Mansfield" "Mablethorpe" "Lutterworth"
  "Lowdham" "Louth" "Loughborough" "Long Eaton" "Littleover"
  "Little Houghton" "Lincoln" "Leicester" "Langar" "Kirton"
  "Kirkby-in-Ashfield" "Kirk Langley" "Kibworth Harcourt" "Kettering"
  "Kegworth" "Irthlingborough" "Irchester" "Ingoldmells" "Ilkeston"
  "Huthwaite" "Hucknall" "Horton" "Horncastle" "Hope" "Holbrook"
  "Holbeach" "Hinckley" "Higham Ferrers" "Heanor" "Hatton" "Groby"
  "Gretton" "Grantham" "Grafton Regis" "Goulceby" "Glossop"
  "Gainsborough" "Fleckney" "Eastwood" "Duston" "Duffield" "Dronfield"
  "Draycott" "Donington on Bain" "Doe Lea" "Derby" "Daventry" "Crowland"
  "Crick" "Crich" "Cranwell" "Countesthorpe" "Costock" "Corringham"
  "Corby" "Coalville" "Chilwell" "Chesterfield" "Chatsworth" "Charnwood"
  "Chapel-en-le-Frith" "Castle Donington" "Calverton" "Caldwell"
  "Buxworth" "Buxton" "Burton Latimer" "Broughton Astley" "Broughton"
  "Brixworth" "Braunston" "Branston" "Brackley" "Bourne"
  "Boston" "Bolsover" "Blisworth" "Blaby" "Bingham" "Billinghay"
  "Billingborough" "Belper" "Beeston" "Barrow-on-Soar" "Bakewell"
  "Ashby-de-la-Zouch" "Ashbourne" "Arnold" "Allestree" "Alfreton"
  "Alford"
 "Yaxley" "Wymondham" "Wroxham" "Writtle" "Woodbridge"
  "Witham" "Wisbech" "Willingham" "Widdington" "Wickford" "Whittlesey"
  "White Roding" "Wherstead" "Wethersfield" "Westcliff"
  "Wells-next-the-Sea" "Waterbeach" "Walton-on-the-Naze" "Waltham Abbey"
  "Trumpington" "Troston" "Tollesbury" "Tiptree" "Tilbury" "Thundersley"
  "Thornham" "Thetford" "Thaxted" "Swavesey" "Swaffham Bulbeck" "Sudbury"
  "Stratford St. Mary" "Stragglethorpe" "Stowmarket" "Steeple Morden"
  "Stanton" "Stansted" "St. Neots" "St. Ives" "Southwold"
  "Southend-on-Sea" "South Woodham Ferrers" "Soham" "Snettisham" "Snape"
  "Sizewell" "Shoeburyness" "Sheringham" "Shenfield" "Saxmundham"
  "Sawtry" "Sawston" "Saffron Walden" "Romford" "Rochford" "Rayleigh"
  "Ramsey" "Purfleet" "Prickwillow" "Pitsea" "Pilgrims Hatch"
  "Peterborough" "Over" "Otley" "Norwich" "North Walsham" "Newmarket"
  "New Wimpole" "Needham Market" "Nazeing" "Nayland" "Mundesley" "Milton"
  "Mildenhall" "Metfield" "Melbourn" "Marks Tey" "March" "Manningtree"
  "Manea" "Maldon" "Ludham" "Lowestoft" "Loughton" "Long Melford"
  "Loddon" "Linton" "Leiston" "Leigh-on-Sea" "Lavenham" "Langham"
  "Lamarsh" "Lakenheath" "King's Lynn" "Kimbolton" "Kettlestone"
  "Kesgrave" "Kelvedon Hatch" "Isleham" "Ipswich" "Ingatestone" "Ilford"
  "Huntingdon" "Hunstanton" "Hornchurch" "Holt" "Holbrook" "Hockley"
  "Haverhill" "Harwich" "Harlow" "Harleston" "Hardwick" "Halstead"
  "Halesworth" "Hadleigh" "Hacheston" "Great Yarmouth" "Great Dunmow"
  "Grays" "Godmanchester" "Framsden" "Framlingham" "Feltwell" "Felsted"
  "Felixstowe" "Fakenham" "Eye" "Epping" "Ely" "Easton" "Downham Market"
  "Ditchingham" "Diss" "Dereham" "Debenham" "Culford Park" "Cromer"
  "Cringleford" "Crays Hill" "Costessey" "Colchester" "Coggeshall"
  "Cley next the Sea" "Clare" "Clacton-on-Sea" "Chipping Ongar" "Chigwell"
  "Chelmsford" "Chatteris" "Chappel" "Cawston" "Canvey Island"
  "Cambridge" "California" "Bury St. Edmunds" "Burwell"
  "Burnham-on-Crouch" "Burnham Market" "Bures" "Bungay" "Buckhurst Hill"
  "Buckden" "Brundall" "Brightlingsea" "Brentwood" "Braintree"
  "Bradwell-on-Sea" "Bourn" "Bottisham" "Borley" "Bobbingworth"
  "Blakesley" "Blakeney" "Billericay" "Benfleet" "Beccles" "Basildon"
  "Barton Mills" "Barling" "Banham" "Bacton" "Aylsham" "Aylmerton"
  "Audley End" "Attleborough" "Aslacton" "Asheldham" "Aldeburgh" "Acle"
  "Abington"
 "West Auckland" "Stanley" "Spennymoor" "Shildon" "Sedgefield"
  "Seaham" "Peterlee" "Newton Aycliffe" "Lanchester" "Ebchester" "Easington"
  "Durham" "Darlington" "Consett" "Chester-le-Street" "Bishop Auckland"
  "Barnard Castle"
 "Yetminster" "Worth Matravers" "Wimborne" "Weymouth" "Wareham"
  "Verwood" "Tolpuddle" "Swanage" "Sturminster Newton" "St. Ives" "Sherborne"
  "Shaftesbury" "Sandford" "Puddletown" "Portland" "Poole" "Parkstone"
  "Lyme Regis" "Langton Matravers" "Holwell" "Gillingham" "Ferndown"
  "Dorchester" "Corfe Castle" "Christchurch" "Charmouth" "Broadstone"
  "Bridport" "Bournemouth" "Blandford Forum" "Abbotsbury"
 "Yettington" "Yelverton" "Woolacombe" "Westward Ho!" "Westleigh"
  "West Down" "Uffculme" "Totnes" "Torquay" "Topsham" "Tiverton" "Teignmouth"
  "Tavistock" "Stokenham" "Stoke" "Sowton" "South Molton" "South Brent"
  "Sidmouth" "Shirwell" "Shebbear" "Shaldon" "Seaton" "Salcombe" "Rattery"
  "Plympton" "Plymouth" "Pennymoor" "Parracombe" "Paignton" "Ottery St. Mary"
  "Okehampton" "Newton Abbot" "Moretonhampstead" "Merton" "Marldon" "Lynton"
  "Lynmouth" "Lifton" "Kingsteignton" "Kingsbridge" "Ivybridge" "Ilfracombe"
  "Honiton" "Holsworthy" "Holbeton" "Hemyock" "Heathfield" "Hatherleigh"
  "Harbertonford" "Great Torrington" "Exmouth" "Exeter" "Drewsteignton"
  "Dolton" "Dawlish" "Dartmouth" "Cullompton" "Croyde" "Crediton"
  "Combe Martin" "Colyford" "Clovelly" "Chudleigh" "Challacombe" "Burrington"
  "Budleigh Salterton" "Buckfastleigh" "Brixham" "Braunton" "Bradworthy"
  "Bradninch" "Bovey Tracey" "Bideford" "Berrynarbor" "Beaworthy" "Barnstaple"
  "Bampton" "Babbacombe" "Axminster" "Ashburton" "Appledore" "Abbotskerswell"
 "Wirksworth" "Willington" "Whaley Bridge" "Tansley"
  "Swadlincote" "Stonebroom" "Spondon" "Somercotes" "Ripley" "Repton" "Newbold"
  "New Mills" "Morton" "Melbourne" "Matlock" "Mapperley" "Long Eaton"
  "Littleover" "Ilkeston" "Hope" "Holbrook" "Heanor" "Hatton" "Glossop"
  "Duffield" "Dronfield" "Draycott" "Doe Lea" "Derby" "Crich" "Chesterfield"
  "Chatsworth" "Chapel-en-le-Frith" "Caldwell" "Buxworth" "Buxton" "Bolsover"
  "Belper" "Bakewell" "Ashbourne" "Allestree" "Alfreton"
 "Workington" "Windermere" "Wigton" "Whitehaven" "Ulverston"
  "Staveley" "St. Bees" "Shap" "Sedbergh" "Ravenglass" "Penrith" "Newby Bridge"
  "Milnthorpe" "Millom" "Maryport" "Low Crosby" "Kirkoswald" "Kirkby Stephen"
  "Kirkby Lonsdale" "Keswick" "Kentmere" "Kendal" "Hawkshead" "Greystoke"
  "Great Asby" "Grasmere" "Grange-over-Sands" "Gosforth" "Eamont Bridge"
  "Dalton-in-Furness" "Crosby Garrett" "Coniston" "Cockermouth" "Cartmel"
  "Carlisle" "Caldbeck" "Buttermere" "Broughton-in-Furness" "Brampton"
  "Bowness-on-Windermere" "Bassenthwaite" "Barrow-in-Furness"
  "Appleby-in-Westmorland" "Ambleside" "Alston"

 "Whitstone" "Wadebridge" "Truro" "Torpoint" "Tintagel"
  "St. Keverne" "St. Just" "St. Ives" "St. Germans" "St. Columb Major"
  "St. Blazey" "St. Austell" "St. Agnes" "Saltash" "Redruth" "Porthleven"
  "Port Isaac" "Polzeath" "Polperro" "Perranporth" "Penzance" "Penryn" "Par"
  "Padstow" "Newquay" "Mullion" "Mousehole" "Mevagissey" "Marazion"
  "Lostwithiel" "Looe" "Lizard" "Liskeard" "Launceston" "Herodsfoot" "Helston"
  "Hayle" "Halsetown" "Gunnislake" "Fowey" "Falmouth" "Davidstow" "Coverack"
  "Chapel Amble" "Camelford" "Camborne" "Callington" "Bude" "Boscastle"
  "Bodmin"
 "Yarm" "Thornaby-on-Tees" "Teesside" "Stockton-on-Tees"
  "Saltburn" "Redcar" "Nunthorpe" "Middlesbrough" "Marske-by-Sea"
  "Haverton Hill" "Hartlepool" "Billingham"
 "Wistaston" "Winsford" "Wincham" "Wilmslow" "Widnes" "Warrington"
  "Tarporley" "Stockton Heath" "Sandbach" "Sale" "Runcorn" "Prestbury"
  "Poynton" "Penketh" "Northwich" "Neston" "Nantwich" "Middlewich" "Malpas"
  "Macclesfield" "Lymm" "Lower Whitley" "Knutsford" "Kingsley" "Holmes Chapel"
  "Haslington" "Handforth" "Hale" "Frodsham" "Faddiley" "Ellesmere Port"
  "Daresbury" "Culcheth" "Crewe" "Congleton" "Chester" "Bollington" "Alsager"
  "Alderley Edge"
 "Yaxley" "Wisbech" "Willingham" "Whittlesey" "Trumpington"
  "Thorney" "Swavesey" "Swaffham Bulbeck" "Steeple Morden" "St. Neots"
  "St. Ives" "Soham" "Shepreth" "Sawtry" "Sawston" "Ramsey" "Prickwillow"
  "Peterborough" "Over" "New Wimpole" "Milton" "Melbourn" "March" "Manea"
  "Linton" "Kimbolton" "Huntingdon" "Hardwick" "Godmanchester" "Ely" "Duxford"
  "Chatteris" "Cambridge" "Burwell" "Buckden" "Bourn" "Bottisham" "Abington"
 "Wooburn Green" "Winslow" "Weston Turville" "Wendover"
  "Stokenchurch" "Stoke Poges" "Stoke Mandeville" "Soulbury" "Richings Park"
  "Princes Risborough" "Olney" "Newport Pagnell" "Naphill" "Milton Keynes"
  "Mentmore" "Marlow" "Iver" "High Wycombe" "Haddenham" "Great Missenden"
  "Gerrards Cross" "Farnham Royal" "Chesham" "Chalfont St. Peter"
  "Chalfont St. Giles" "Buckingham" "Bourne End" "Bletchley" "Bierton"
  "Beaconsfield" "Aylesbury" "Aston Clinton" "Amersham"
 "Woodley" "Wokingham" "Winnersh" "Windsor" "Wickham" "Wargrave"
  "Upper Bucklebury" "Twyford" "Theale" "Thatcham" "Swallowfield" "Sunninghill"
  "Sunningdale" "Spencers Wood" "Speen" "Slough" "Sindlesham" "Sandhurst"
  "Reading" "Pangbourne" "Oakley Green" "Newbury" "Maidenhead" "Langley"
  "Lambourn" "Hungerford" "Finchampstead" "Datchet" "Crowthorne" "Cookham"
  "Compton" "Chieveley" "Caversham" "Burchett's Green" "Bray" "Bracknell"
  "Binfield" "Ascot" "Aldermaston"
 "Wootton" "Woburn" "Turvey" "Stotfold" "Shefford" "Sandy"
  "Pulloxhill" "Potton" "Oakley" "Luton" "Linslade" "Lidlington"
  "Leighton Buzzard" "Kensworth" "Kempston" "Houghton Regis" "Harlington"
  "Flitwick" "Dunstable" "Cranfield" "Cople" "Caddington" "Biggleswade"
  "Bedford" "Barton-le-Clay" "Ampthill"
 "Yate" "Weston-super-Mare" "Timsbury" "Thornbury" "Radstock"
  "Portishead" "Nailsea" "Long Ashton" "Keynsham" "Frampton Cotterell"
  "Fishponds" "Farmborough" "Congresbury" "Clutton" "Clifton" "Clevedon"
  "Chew Magna" "Bristol" "Brislington" "Bradley Stoke" "Bath"
"Bedford" "Luton" "Dunstable" "Leighton Buzzard" "Biggleswade" "Sandy" "hersham" "epping"
		       "Reading" "Bracknell" "Maidenhead" "Newbury" "Windsor" "Wokingham" "Abingdon" "godalming"
		       "Aylesbury" "Milton Keynes" "Slough" "Buckingham" "High Wycombe" "city of westminster"
		       "Cambridge" "Wisbech" "Ely" "March" "Whittlesey" "Chatteris" "Linton" "pershore"
		       "Chester" "Stockport" "Birkenhead" "Wallasey" "Runcorn" "Macclesfield" "Crewe"
		       "Bodmin" "Truro" "Camborne" "Redruth" "St. Austell" "Falmouth" "Penzance" "Newquay"
		       "Carlisle" "Whitehaven" "Workington" "Penrith" "Keswick" "Brampton" "wrexham"
		       "Derby" "Chesterfield" "Ilkeston" "Swadlincote" "Buxton" "Matlock" "Ashbourne" "altrincham"
		       "Exeter" "Plymouth" "Torquay" "Paignton" "Barnstaple" "Tiverton" "Newton Abbot" "Tavistock"
		       "Dorchester" "Poole" "Weymouth" "Sherborne" "Wimborne Minster" "Shaftesbury" "doncaster"
		       "Durham" "Sunderland" "Stockton-on-Tees" "Darlington" "Hartlepool" "Gateshead" "Washington"
		       "Chelmsford" "Basildon" "Romford" "Southend" "Colcheter" "Harlow" "Brentwood" "West Ham"
		       "Gloucester" "Bristol" "Cheltenham" "Stroud" "Cirencester" "Tewkesbury"
		       "Winchester" "Southampton" "Portsmouth" "Bournemouth" "Basingstoke" "Newport"
		       "Hereford" "Ross-on-Wye" "Leominster" "Ledbury" "Bromyard" "Kington"
		       "Hertford" "Watford" "St. Albans" "Hemel Hempstead" "Stevenage" "Hatfield"
		       "Huntingdon" "St. Ives" "St. Neots" "Ramsey" "Yaxley" "london" "barrow-upon-humber"
		       "Maidstone" "Canterbury" "Bromley" "Rochester" "Margate" "Folkestone" "Dover" "Greenwich"
		       "Lancaster" "Liverpool" "Manchester" "Preston" "Bolton" "Warrington" "Barrow-in-Furness"
		       "Leicester" "Loughborough" "Hinckley" "Melton Mowbray" "Coalville" "Lutterworth"
		       "Lincoln" "Grimsby" "Scunthorpe" "Boston" "Grantham" "Stamford" "Skegness" "Louth"
		       "City of London" "Harrow" "Enfield" "Staines" "Ealing" "Potters Bar" "Westminster" 
		       "Norwich" "King's Lynn" "Dereham" "Cromer" "Hunstanton"
		       "Northampton" "Peterborough" "Corby" "Kettering" "Wellingborough"
		       "Alnwick" "Newcastle-upon-Tyne" "Morpeth" "Hexham" "Berwick-upon-Tweed"
		       "Nottingham" "Mansfield" "Worksop" "Newark" "Retford" "Southwell"
		       "Oxford" "Banbury" "Witney" "Bicester" "Henley-on-Thames" "Carterton" "Thame"
		       "Oakham" "Uppingham" "Cottesmore"
		       "Shrewsbury" "Telford" "Oswestry" "Bridgnorth" "Whitchurch" "Market Drayton" "Ludlow"
		       "Taunton" "Bath" "Weston-super-Mare" "Yeovil" "Bridgwater" "Wells" "Glastonbury"
		       "Stafford" "Stoke-on-Trent" "Wolverhampton" "Walsall" "Cannock" "Lichfield"
		       "Ipswich" "Bury St. Edmunds" "Lowestoft" "Felixstowe" "Sudbury" "Haverhill" "Bungay"
		       "Guildford" "Croydon" "Woking" "Sutton" "Kingston-on-Thames" "Wandsworth" "Wimbledon" "Brixton"
		       "Chichester" "Brighton" "Worthing" "Crawley" "Hastings" "Eastbourne" "Bognor Regis" "Horsham"
		       "Warwick" "Birmingham" "Coventry" "Nuneaton" "Rugby" "Solihull" "Stratford-upon-Avon"
		       "Appleby" "Kendal" "Windermere" "Ambleside" "Kirkby Lonsdale"
		       "Trowbridge" "Salisbury" "Swindon" "Chippenham" "Devizes" "Marlborough" "Warminster"
		       "Worcester" "Dudley" "Kidderminster" "Stourbridge" "Halesowen" "Malvern" "Evesham"
		       "Northallerton" "Middlesbrough" "Scarborough" "Whitby"
		       "Beverley" "Hull" "Bridlington" "Driffield" "Hornsea" "Filey"
		       "Wakefield" "Leeds" "Sheffield" "Bradford" "Halifax" "Harrogate" "York"
		       "Beaumaris" "Holyhead" "Llangefni" "Amlwch" "Menai Bridge"
		       "Brecon" "Builth Wells" "Hay-on-Wye" "Talgarth" "Llanwrtwd Wells"
		       "Caernarfon" "Bangor" "Llandudno" "Conwy" "Pwllheli" "Porthmadog"
		       "Carmarthen" "Llanelli" "Ammanford" "Llandovery" "Kidwelly" "St. Clears"
		       "Cardigan" "Aberystwyth" "Lampeter" "New Quay" "Tregaron"
		       "Denbigh" "Wrexham" "Ruthin" "Abergele" "Llangollen"
		       "Mold" "Flint" "Rhyl" "Prestatyn" "Connah's Quay" "Holywell" "Buckley" "St. Asaph"
		       "Cardiff" "Swansea" "Merthyr Tydfil" "Barry" "Caerphilly" "Bridgend" "Neath" "Pontypridd"
		       "Dolgellau" "Bala" "Tywyn" "Blaenau Ffestiniog" "Barmouth" "Harlech"
		       "Monmouth" "Newport" "Blackwood" "Cwmbran" "Abergavenny" "Chepstow" "Tredegar"
		       "Montgomery" "Newtown" "Welshpool" "Machynlleth" "Llanidloes"
		       "Pembroke" "Milford Haven" "Haverfordwest" "Fishguard" "Tenby" "St. David's"
		       "Presteigne" "Llandrindod Wells" "Knighton" "Rhayader" "New Radnor"
		       "Aberdeen" "Peterhead" "Fraserburgh" "Inverurie" "Huntley" "Ellon" "Turriff"
		       "Forfar" "Dundee" "Arbroath" "Brechin" "Montrose" "Carnoustie" "Kirriemuir"
		       "Inveraray" "Oban" "Dunoon" "Campbeltown" "Lochgilphead" "Tobermory"
		       "Ayr" "Kilmarnock" "Irvine" "Saltcoats" "Kilwinning" "Largs" "Troon" "Cumnock"
		       "Banff" "Buckie" "Keith" "Macduff" "Portsoy" "Dufftown"
		       "Greenlaw" "Duns" "Eyemouth" "Lauder" "Coldstream"
		       "Rothesay" "Millport" "Brodick" "Lochranza"
		       "Cromarty" "Ullapool" "Wick" "Thurso" "Halkirk" "Castletown"
		       "Clackmannan" "Alloa" "Tillicoultry" "Tullibody"
		       "Dumfries" "Annan" "Lockerbie" "Moffat" "Sanquhar" "Langholm" "Gretna"
		       "Dumbarton" "Clydebank" "Cumbernauld" "Helensburgh" "Alexandria" "Kirkintilloch"
		       "Haddington" "North Berwick" "Dunbar" "Tranent" "East Linton"
		       "Cupar" "Dunfermline" "Glenrothes" "Kirkcaldy" "St. Andrews" "Cowdenbeath" "Burntisland"
		       "Inverness" "Fort William" "Kingussie" "Newtonmore" "Portree"
		       "Stonehaven" "Banchory" "Laurencekirk" "Inverbervie"
		       "Kinross" "Milnathort" "Kircudbright" "Castle Douglas" "Dalbeattie" "New Galloway"
		       "Lanark" "Glasgow" "East Kilbride" "Hamilton" "Motherwell" "Coatbridge" "Carluke"
		       "Edinburgh" "Musselburgh" "Penicuik" "Dalkeith" "Bonnyrigg"
		       "Elgin" "Forres" "Rothes" "Lossiemouth" "Fochabers"
		       "Nairn" "Auldearn" "Cawdor" "Ferness"
		       "Kirkwall" "Sromness" "Balfour"
		       "Peebles" "Innerleithen" "West Linton"
		       "Perth" "Crieff" "Pitlochry" "Callander" "Blairgowrie" "Rattray" "Coupar Angus" "Kincardine"
		       "Renfrew" "Paisley" "Greenock" "Johnstone" "Port Glasgow" "Barrhead" "Kilmalcolm"
		       "Dingwall" "Stornaway" "Tain" "Alness" "Invergorden"
		       "Jedburgh" "Hawick" "Kelso" "Melrose" "Roxburgh"
		       "Selkirk" "Clovenfords" "Galashiels"
		       "Lerwick" "Scalloway" "Baltasound"
		       "Stirling" "Falkirk" "Grangemouth" "Kilsyth" "Bridge of Allan" "Denny" "Alva"
		       "Dornoch" "Helmsdale" "Brora" "Golspie" "Lairg" "Durness" "Tongue"
		       "Linlithgow" "Livingston" "Bo'ness" "Broxburn" "Whitburn" "Armadale" "Bathgate"
		       "Wigtown" "Stranraer" "Newton Stewart" "Whithorn"))
  :test #'string=))

(defparameter *number-scanner* (cl-ppcre:create-scanner "\\b((PLOT |UNIT |)?[A-Z]?[0-9]+[A-Z]?( APARTMENT| SUITE|)?|[A-Z0-9 ]*FLAT[A-Z0-9 ]*)\\b")) ; # or flat # or # Apartment or # Suite or Plot #
(defparameter *word-scanner* (cl-ppcre:create-scanner "[A-Za-z0-9'\\- \\&]+")) 
(defparameter *spaces* (cl-ppcre:create-scanner "[ ]{2,}"))
(defparameter *postcode-scanner* (cl-ppcre:create-scanner "\\b[A-PR-UWYZ][A-HK-Y0-9][A-HJKSTUW0-9]?[ABEHMNPRVWXY0-9]? {1,2}[0-9][ABD-HJLN-UW-Z]{2}\\b|GIR 0AA"))
(defparameter *main-postcode-scanner* (cl-ppcre:create-scanner "\\b[A-PR-UWYZ][A-HK-Y0-9][A-HJKSTUW0-9]?[ABEHMNPRVWXY0-9]?\\b|GIR"))
(defparameter *detail-postcode-scanner* (cl-ppcre:create-scanner "\\b{1,2}[0-9][ABD-HJLN-UW-Z]{2}\\b|0AA"))

(defparameter *common-occurances-street* (mapcar #'string-upcase '("ROAD" "STREET" "CLOSE" "LANE" "WAY")))
(defparameter *common-occurances-house-name* (mapcar #'string-upcase '("Place" "court" "wharf" "lodge" "mews" "walk" "house" "cottage" "end" "hill" "mansions" "studios" "farm" "hall" "barns" "bungalow" "view" "club")))

(fact (address :num :street :town :town :county :pc))
(fact (address :name :num :street :town :town :county :pc))
(fact (address :num :street :town :area :county :pc))
(fact (address :num :street :town :county :pc))
(fact (address :name :num :street :town :county :pc))
(fact (address :name :street :town :area :county :pc))
(fact (address :name :num :street :area :town :county :pc))
(fact (address :num :num :street :town :county :pc))
(fact (address :num :street :town :county :pc))
(fact (address :num :street :town :pc))
(fact (address :name :street :area :town :pc))
(fact (address :num :num :street :area :town :county :pc))
(fact (address :num :name :street :town :pc))
(fact (address :num :street :area :area :town :pc))
(fact (address :name :town :county :pc))

(defparameter *places* (make-hash-table :size 1500000))
(defparameter *docs* (make-hash-table :size 5000000))

(defun read-places ()
  (let ((docid 0)
	(lastpos 1))
    (with-open-file (in (sondesh-file-path "pcs/houses/try-addresses"))
      (do ((line (read-line in nil)
		 (read-line in nil)))
	  ((null line))
	(when line
	  (let ((doc (incf docid)))
	    (setf (gethash doc *docs*) lastpos)
	    (incf lastpos (length line))
	    (dolist (part-kind (parse-address line))
	      (index-part doc part-kind))))))))

(defun index-part (docid part-kind)
  (let ((sym (make-logic-symbol (cl-ppcre:regex-replace-all "[ \\-\\&\\.']" (car part-kind) ""))))
    (aif (gethash sym *places*)
	 (setf (gethash sym *places*) (cons (cons docid (cdr part-kind)) (gethash sym *places*)))
	 (setf (gethash sym *places*) (cons docid (cdr part-kind))))))

(defun parse-address (address)
  (labels ((town-p (val) (find (cl-ppcre:regex-replace-all "[ \\-\\&\\.']" val "") *town* :test #'string=))
	   (county-p (val) (find (cl-ppcre:regex-replace-all "[ \\-\\&\\.']" val "") *county* :test #'string=))
	   (postcode-p (val) (awhen (cl-ppcre:all-matches-as-strings *postcode-scanner* val)
			       (string= (first it) val)))
	   (number-p (val) (awhen (cl-ppcre:all-matches-as-strings *number-scanner* val)
				  (string= (first it) val)))
	   (get-next-token (val)
	     (if (string= val "")
		 nil
		 (if (town-p val)
		     (cons val :town)
		     (if (county-p val)
			 (cons val :county)
			 (if (postcode-p val)
			     (cons val :pc)
			     (if (number-p val)
				 (cons val :num)
				 (cons val (make-logic-symbol (concatenate 'string "?" (symbol-name (gensym))))))))))))
    (let* ((pattern (remove-if 
		     #'not
		     (mapcar (compose #'get-next-token #'(lambda (place) (cl-ppcre:regex-replace-all *spaces* place " ")) #'string-upcase #'trim)
			     (cl-ppcre:all-matches-as-strings *word-scanner* address))))
	   (results '())
	   (matches (prove-all (list (cons 'address (mapcar #'cdr pattern))) *no-bindings*)))
      (dolist (var pattern)
	(aif (find (cdr var) (car matches) :key #'car)
	     (push (cons (car var) (cdr it)) results)
	     (push var results)))
      (values (nreverse results) pattern))))
